package com.example.assignment3_3;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.FlowPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.shape.Circle;
import javafx.stage.Stage;

import java.io.IOException;
import java.util.ArrayList;
import java.util.concurrent.Executor;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;


/**
 * The ball class is the class used to show a window. This is a subclass of the Application class.
 *:::::
 * */
public class Ball extends Application {
    /**
     * The ballTahtBounce filed is an Arraylist storing all the ball generated by the user
     * */
    private ArrayList<AbleToBounce> ballThatBounce;
    /**
     * ballgroup is a GridPane field used to put the balls on it.
     * */
    private GridPane ballgroup;
    private final int WINDOW_WIDTH = 500;
    private final int WINDOW_HEIGHT = 500;
    private ExecutorService executor;
    @Override
    public void start(Stage stage) throws IOException {
        Label title = new Label("click anywhere to throw the ball.");
        this.ballThatBounce = new ArrayList<AbleToBounce>();
       this.ballgroup = new GridPane();
       this.ballgroup.setVgap(1.0);
       this.ballgroup.setHgap(1.0);
       this.ballgroup.addEventHandler(MouseEvent.MOUSE_CLICKED, event -> {
           if (ballThatBounce.isEmpty()) {
               bouncing(event.getSceneX(), event.getSceneY());
           }
       });
       this.executor = Executors.newFixedThreadPool(2);
       this.executor.submit(() -> {
           actualise();
       });
        Scene scene = new Scene(ballgroup, WINDOW_WIDTH, WINDOW_HEIGHT);
        stage.setTitle("Bouncing Ball");
        stage.setScene(scene);
        ballgroup.getChildren().add(title);
        stage.show();
    }
    public void borderTouch(int n) {
        int i = 0;
        boolean touch = false;
        while(i < this.ballThatBounce.size() && !touch) {
            this.ballThatBounce.get(i).BorderColideHandler(this.WINDOW_WIDTH, this.WINDOW_HEIGHT);
            i++;
        }
    }
    public void bouncing(double x, double y) {
        int xSpeed = Math.random() > 0.5 ? 1 : -1;
        //xSpeed *= Math.random() > 0.5 ? 1 : -1;
        int ySpeed = Math.random() > 0.5 ? 1 : -1;
        //ySpeed *= Math.random() > 0.5 ? 1 : -1;
        this.ballThatBounce.add(new AbleToBounce(x - 12.5, y - 12.5,25.0, xSpeed, ySpeed));
        int ballNumber = this.ballThatBounce.size() - 1;
        this.ballgroup.getChildren().add(ballThatBounce.get(ballNumber));
    }
    public void actualise() {
        while(true) {
            System.out.println();
            if (!ballThatBounce.isEmpty()) {
                for (int i = 0; i < ballThatBounce.size(); i++) {
                    try {
                        Thread.sleep(20);
                        ballThatBounce.get(i).setCenterX(ballThatBounce.get(i).getCenterX() + ballThatBounce.get(i).getXSpeed());
                        ballThatBounce.get(i).setCenterY(ballThatBounce.get(i).getCenterY() + ballThatBounce.get(i).getYSpeed());
                        ballThatBounce.get(i).setTranslateX(ballThatBounce.get(i).getCenterX() + ballThatBounce.get(i).getXSpeed());
                        ballThatBounce.get(i).setTranslateY(ballThatBounce.get(i).getCenterY() + ballThatBounce.get(i).getYSpeed());
                        borderTouch(i);
                    } catch (InterruptedException e) {
                        System.out.println("ERRORRR");
                    }
                }
            }
        }
        }
    public static void main(String[] arg) {
        launch(arg);
    }
}
